### ISSUE TITLE
Old Node versions support

### ISSUE THREAD

**Issue by kinday** [iamstarkov/generator-underhood#6]
Hey! I’ve noticed v0.10 and v0.12 in Travis config. I think it’s not necessary to support them as they are kinda obsolete.

The main benefits I see in dropping ’em are:
— stimulation for adoption of up-to-date technologies;
— opportunity to use some of ES2015 features, arrow functions and `const`/`let` declarations mainly.

This is more of a discussion but if you find this proposal to be reasonable I could help with refactoring.

**Comment by iamstarkov** [comment]
> — stimulation for adoption of up-to-date technologies;

npm tried this strategy and discovered that it doesnt work.

> — opportunity to use some of ES2015 features, arrow functions and const/let declarations mainly.

we do have babel for this, dont we?

Also, I would like to keep all LTS nodejs versions as long as possible, as far as it doesnt cost that much to support

**Comment by kinday** [comment]
> npm tried this strategy and discovered that it doesnt work

I don’t get what you’re talking about. Can you share a link?
